require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoilFilmMappingsController do

  # This should return the minimal set of attributes required to create a valid
  # CoilFilmMapping. As you add validations to CoilFilmMapping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "coil_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoilFilmMappingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coil_film_mappings as @coil_film_mappings" do
      coil_film_mapping = CoilFilmMapping.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coil_film_mappings).should eq([coil_film_mapping])
    end
  end

  describe "GET show" do
    it "assigns the requested coil_film_mapping as @coil_film_mapping" do
      coil_film_mapping = CoilFilmMapping.create! valid_attributes
      get :show, {:id => coil_film_mapping.to_param}, valid_session
      assigns(:coil_film_mapping).should eq(coil_film_mapping)
    end
  end

  describe "GET new" do
    it "assigns a new coil_film_mapping as @coil_film_mapping" do
      get :new, {}, valid_session
      assigns(:coil_film_mapping).should be_a_new(CoilFilmMapping)
    end
  end

  describe "GET edit" do
    it "assigns the requested coil_film_mapping as @coil_film_mapping" do
      coil_film_mapping = CoilFilmMapping.create! valid_attributes
      get :edit, {:id => coil_film_mapping.to_param}, valid_session
      assigns(:coil_film_mapping).should eq(coil_film_mapping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoilFilmMapping" do
        expect {
          post :create, {:coil_film_mapping => valid_attributes}, valid_session
        }.to change(CoilFilmMapping, :count).by(1)
      end

      it "assigns a newly created coil_film_mapping as @coil_film_mapping" do
        post :create, {:coil_film_mapping => valid_attributes}, valid_session
        assigns(:coil_film_mapping).should be_a(CoilFilmMapping)
        assigns(:coil_film_mapping).should be_persisted
      end

      it "redirects to the created coil_film_mapping" do
        post :create, {:coil_film_mapping => valid_attributes}, valid_session
        response.should redirect_to(CoilFilmMapping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coil_film_mapping as @coil_film_mapping" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoilFilmMapping.any_instance.stub(:save).and_return(false)
        post :create, {:coil_film_mapping => { "coil_id" => "invalid value" }}, valid_session
        assigns(:coil_film_mapping).should be_a_new(CoilFilmMapping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoilFilmMapping.any_instance.stub(:save).and_return(false)
        post :create, {:coil_film_mapping => { "coil_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coil_film_mapping" do
        coil_film_mapping = CoilFilmMapping.create! valid_attributes
        # Assuming there are no other coil_film_mappings in the database, this
        # specifies that the CoilFilmMapping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoilFilmMapping.any_instance.should_receive(:update_attributes).with({ "coil_id" => "MyString" })
        put :update, {:id => coil_film_mapping.to_param, :coil_film_mapping => { "coil_id" => "MyString" }}, valid_session
      end

      it "assigns the requested coil_film_mapping as @coil_film_mapping" do
        coil_film_mapping = CoilFilmMapping.create! valid_attributes
        put :update, {:id => coil_film_mapping.to_param, :coil_film_mapping => valid_attributes}, valid_session
        assigns(:coil_film_mapping).should eq(coil_film_mapping)
      end

      it "redirects to the coil_film_mapping" do
        coil_film_mapping = CoilFilmMapping.create! valid_attributes
        put :update, {:id => coil_film_mapping.to_param, :coil_film_mapping => valid_attributes}, valid_session
        response.should redirect_to(coil_film_mapping)
      end
    end

    describe "with invalid params" do
      it "assigns the coil_film_mapping as @coil_film_mapping" do
        coil_film_mapping = CoilFilmMapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoilFilmMapping.any_instance.stub(:save).and_return(false)
        put :update, {:id => coil_film_mapping.to_param, :coil_film_mapping => { "coil_id" => "invalid value" }}, valid_session
        assigns(:coil_film_mapping).should eq(coil_film_mapping)
      end

      it "re-renders the 'edit' template" do
        coil_film_mapping = CoilFilmMapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoilFilmMapping.any_instance.stub(:save).and_return(false)
        put :update, {:id => coil_film_mapping.to_param, :coil_film_mapping => { "coil_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coil_film_mapping" do
      coil_film_mapping = CoilFilmMapping.create! valid_attributes
      expect {
        delete :destroy, {:id => coil_film_mapping.to_param}, valid_session
      }.to change(CoilFilmMapping, :count).by(-1)
    end

    it "redirects to the coil_film_mappings list" do
      coil_film_mapping = CoilFilmMapping.create! valid_attributes
      delete :destroy, {:id => coil_film_mapping.to_param}, valid_session
      response.should redirect_to(coil_film_mappings_url)
    end
  end

end
